name: Deploy Assets to FTP
'on':
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
      - name: 🔨 Build Project
        run: npm run build
      - name: 📂 Sync assets files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.digimoncard.app
          port: 21
          username: ${{ secrets.PROD_USER }}
          password: ${{ secrets.PROD_PASSWORD }}
          local-dir: ./dist/assets/
          server-dir: ./public_html/
      - name: 📂 Sync server files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.digimoncard.app
          port: 21
          username: ${{ secrets.PROD_USER }}
          password: ${{ secrets.PROD_PASSWORD }}
          local-dir: ./dist/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/assets/**
          server-dir: ./public_html/
